# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(720, 490)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_user = QtWidgets.QLineEdit(self.centralwidget)
        self.login_user.setGeometry(QtCore.QRect(229, 260, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.login_user.setFont(font)
        self.login_user.setText("")
        self.login_user.setObjectName("login_user")
        self.login_password = QtWidgets.QLineEdit(self.centralwidget)
        self.login_password.setGeometry(QtCore.QRect(229, 299, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_password.setFont(font)
        self.login_password.setObjectName("login_password")
        self.title_pic = QtWidgets.QLabel(self.centralwidget)
        self.title_pic.setGeometry(QtCore.QRect(20, 40, 680, 153))
        font = QtGui.QFont()
        font.setKerning(False)
        self.title_pic.setFont(font)
        self.title_pic.setText("")
        self.title_pic.setObjectName("title_pic")
        self.title_user = QtWidgets.QLabel(self.centralwidget)
        self.title_user.setGeometry(QtCore.QRect(129, 260, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.title_user.setFont(font)
        self.title_user.setObjectName("title_user")
        self.title_password = QtWidgets.QLabel(self.centralwidget)
        self.title_password.setGeometry(QtCore.QRect(130, 300, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.title_password.setFont(font)
        self.title_password.setObjectName("title_password")
        self.button_login = QtWidgets.QPushButton(self.centralwidget)
        self.button_login.setGeometry(QtCore.QRect(200, 360, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_login.setFont(font)
        self.button_login.setObjectName("button_login")
        self.button_exit = QtWidgets.QPushButton(self.centralwidget)
        self.button_exit.setGeometry(QtCore.QRect(400, 360, 120, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_exit.setFont(font)
        self.button_exit.setObjectName("button_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "我切、我切、我切切切"))
        self.title_user.setText(_translate("MainWindow", "使用者名稱："))
        self.title_password.setText(_translate("MainWindow", "使用者密碼："))
        self.button_login.setText(_translate("MainWindow", "登入系統"))
        self.button_exit.setText(_translate("MainWindow", "離開系統"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
